import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";

import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export const participantPreferencesSchema = z.object({
  tripId: z.string().uuid(),
  localMobility: z.enum(["walk_transit", "car_if_worth_it", "car_ok"]).optional().nullable(),
  accommodationRole: z.enum(["base_only", "part_of_stay", "centerpiece"]).optional().nullable(),
  ambiances: z.array(z.string()).default([]),
  activityCategories: z.array(z.string()).default([]),
  budgetMax: z.number().min(0).max(20000).optional(),
  budgetPriority: z
    .enum(["must_have", "high_priority", "preference", "nice_to_have", "irrelevant", "veto"])
    .default("nice_to_have"),
  durationNightsMin: z.number().int().min(1).max(21).optional(),
  durationNightsMax: z.number().int().min(1).max(21).optional(),
  desiredDestination: z.string().max(120).optional(),
  excludedDestinations: z.array(z.string()).default([]),
  dietaryConstraints: z.array(z.string()).default([]),
  mobilityNotes: z.string().max(500).optional(),
  freeText: z.string().max(1000).optional(),

  // Départ & logement
  departureCity: z.string().max(120).optional(),
  departureFlexKm: z.number().int().min(0).max(10000).default(0),
  dateFlexDays: z.number().int().min(0).max(30).default(0),
  acceptsSharedRoom: z.boolean().default(false),
  roomTypePreference: z.string().max(80).optional(),
  requiredAmenities: z.array(z.string()).default([]),
  minAccommodationRating: z.number().min(0).max(5).optional().nullable(),
  travelPace: z.enum(["plein_programme", "equilibre", "chill"]).optional(),
  preferredTimeSlots: z.array(z.string()).default([]),

  // Champs optionnels UI (ne doivent plus être stripés)
  dealBreakerAmbiances: z.array(z.string()).default([]),
  departureAirportOrStation: z.string().max(80).optional(),
  transportModeAccepted: z.array(z.string()).default(["peu importe"]),
  maxTravelDurationHours: z.number().min(0).max(48).optional(),
  accessibilityNeeds: z.boolean().default(false),
  blackoutDates: z.array(z.string()).default([]),
  groupAgeRange: z.string().max(80).optional(),
  wantedEnvType: z.string().max(120).optional(),
  weatherPreference: z.number().int().min(0).max(2).default(1),
});

export function questionnaireCompletionResult(input: {
  isUpdate: boolean;
  answered: number;
  total: number;
}) {
  return {
    ok: true as const,
    isUpdate: input.isUpdate,
    progress: { answered: input.answered, total: input.total },
    autoGenerated: false as const,
    nextStep: "profile" as const,
  };
}

export type ParticipantPreferencesInput = z.infer<typeof participantPreferencesSchema>;

export function assertQuestionnaireCanBeSubmitted(existing: { submitted_at?: string | null } | null) {
  if (existing?.submitted_at) {
    throw new Error("Ce questionnaire a déjà été envoyé et ne peut plus être modifié.");
  }
}

function normalizeEmail(email: string | undefined | null) {
  return typeof email === "string" ? email.trim().toLowerCase() : undefined;
}

export const getMyParticipantPreferences = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { tripId: string }) => z.object({ tripId: z.string().uuid() }).parse(data))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;

    const trip = await supabase
      .from("trips")
      .select("id, name, event_type, departure_city, owner_id, co_organizer_id, celebrated_person, star_user_id, group_logistics")
      .eq("id", data.tripId)
      .maybeSingle();
    if (trip.error) throw trip.error;
    if (!trip.data) throw new Error("Voyage introuvable");

    // Authorization: only the trip owner or a participant (by user_id or email) can access the questionnaire
    const emailRaw = context.claims?.email as string | undefined;
    const email = normalizeEmail(emailRaw);
    let participantRow = null;
    if (trip.data.owner_id !== userId) {
      if (!email) throw new Error("403 Forbidden: Vous n'êtes pas autorisé à accéder à ce questionnaire (email manquant)");
      const participantCheck = await supabase
        .from("trip_participants")
        .select("id, user_id, email, display_name")
        .eq("trip_id", data.tripId)
        // case-insensitive email match
        .or(`user_id.eq.${userId},email.ilike.${email}`)
        .maybeSingle();
      if (participantCheck.error) throw participantCheck.error;
      if (!participantCheck.data) throw new Error("403 Forbidden: Vous n'êtes pas autorisé à accéder à ce questionnaire");
      participantRow = participantCheck.data;
    } else {
      const ownerCheck = await supabase
        .from("trip_participants")
        .select("id, user_id, email, display_name")
        .eq("trip_id", data.tripId)
        .eq("user_id", userId)
        .maybeSingle();
      if (!ownerCheck.error && ownerCheck.data) {
        participantRow = ownerCheck.data;
      }
    }

    // Determine if current user is the Star and star_mode is secret
    let isSecretStar = false;
    const starUid = trip.data.star_user_id;
    const starMode = (trip.data.group_logistics as any)?.star_mode ?? "secret";

    const isStar = Boolean(starUid && userId === starUid);
    if (isStar && starMode === "secret") {
      isSecretStar = true;
    }

    const prefs = await supabase
      .from("trip_participant_preferences")
      .select("*")
      .eq("trip_id", data.tripId)
      .eq("user_id", userId)
      .maybeSingle();
    if (prefs.error) {
      const msg = String(prefs.error.message || prefs.error);
      if (msg.includes("schema cache") || msg.includes("Could not find") || msg.includes("does not exist")) {
        // Table absente : on laisse le formulaire vide plutôt que de planter la page
        return { trip: trip.data, preferences: null, schemaMissing: true };
      }
      throw prefs.error;
    }

    return { trip: trip.data, preferences: prefs.data ?? null, isSecretStar };
  });

export async function attachParticipantToTrip(
  supabase: SupabaseClient,
  tripId: string,
  userId: string,
  email: string,
) {
  if (supabase.auth?.getUser) {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (user && (user.id !== userId || user.email?.toLowerCase() !== email?.toLowerCase())) {
        return { success: false, error: "Utilisateur non autorisé" };
      }
    } catch {
      /* ignore auth check if mock does not support getUser */
    }
  }

  const { data: updated, error } = await supabase
    .from("trip_participants")
    .update({ user_id: userId, status: "accepte" })
    .eq("trip_id", tripId)
    .ilike("email", email)
    .is("user_id", null)
    .select();

  if (error) throw error;
  if (!updated || updated.length === 0) {
    throw new Error(`No pending invitation found for email ${email} on trip ${tripId}`);
  }
  return updated[0];
}

/**
 * Return participants (id, user_id, email, display_name, status) who have not answered the questionnaire yet.
 * Includes both claimed participants (user_id present but no preferences) and unclaimed invites (user_id null).
 */
export async function listUnansweredParticipants(supabase: any, tripId: string) {
  const [participantsRes, prefsRes] = await Promise.all([
    supabase
      .from("trip_participants")
      .select("id, user_id, email, display_name, status, created_at")
      .eq("trip_id", tripId),
    supabase.from("trip_participant_preferences").select("user_id, submitted_at, updated_at").eq("trip_id", tripId),
  ]);
  if (participantsRes.error) throw participantsRes.error;
  if (prefsRes.error) throw prefsRes.error;

  const participants = participantsRes.data ?? [];
  const answeredUserIds = new Set((prefsRes.data ?? []).map((p: any) => p.user_id).filter(Boolean));

  const unanswered = participants.filter((p: any) => {
    // If participant has a user_id, check if their user_id is in the answered set
    if (p.user_id) return !answeredUserIds.has(p.user_id);
    // If participant has no user_id (unclaimed invite), consider them unanswered
    return true;
  });

  return unanswered;
}

export const declareMyStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: unknown) =>
    z.object({ tripId: z.string().uuid(), status: z.enum(["accepte", "absent"]) }).parse(data),
  )
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;
    const email = (context.claims?.email as string | undefined)?.toLowerCase();

    const { data: part, error: partErr } = await supabase
      .from("trip_participants")
      .select("id")
      .eq("trip_id", data.tripId)
      .or(email ? `user_id.eq.${userId},email.ilike.${email}` : `user_id.eq.${userId}`)
      .maybeSingle();

    if (partErr || !part) {
      throw new Error("Participant introuvable");
    }

    const { error } = await supabase
      .from("trip_participants")
      .update({ status: data.status })
      .eq("id", part.id);

    if (error) throw error;

    if (data.status === "absent") {
      await supabase
        .from("trip_participant_preferences")
        .delete()
        .eq("trip_id", data.tripId)
        .eq("user_id", userId);

      await supabase
        .from("trip_availability")
        .delete()
        .eq("trip_id", data.tripId)
        .eq("user_id", userId);
    }

    return { ok: true, status: data.status };
  });

export const submitParticipantPreferences = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: unknown) => participantPreferencesSchema.parse(data))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;

    // Authorization: ensure the user is owner or a listed participant (by user_id or email)
    const tripRes = await supabase.from("trips").select("id, owner_id, dates_locked").eq("id", data.tripId).maybeSingle();
    if (tripRes.error) throw tripRes.error;
    if (!tripRes.data) throw new Error("Voyage introuvable");
    if (tripRes.data.dates_locked) {
      throw new Error("Le voyage est verrouillé par l'organisateur, tes réponses ne peuvent plus être modifiées.");
    }

    const emailRaw = context.claims?.email as string | undefined;
    const email = normalizeEmail(emailRaw);
    if (tripRes.data.owner_id !== userId) {
      if (!email) throw new Error("403 Forbidden: Vous n'êtes pas autorisé à soumettre ce questionnaire (email manquant)");
      const participantCheck = await supabase
        .from("trip_participants")
        .select("id")
        .eq("trip_id", data.tripId)
        .or(`user_id.eq.${userId},email.ilike.${email}`)
        .maybeSingle();
      if (participantCheck.error) throw participantCheck.error;
      if (!participantCheck.data) throw new Error("403 Forbidden: Vous n'êtes pas autorisé à soumettre ce questionnaire");
    }

    // Validation: prevent inconsistent partial submissions
    const min = (data as any).durationNightsMin;
    const max = (data as any).durationNightsMax;
    if (typeof min === "number" && typeof max === "number" && min > max) {
      throw new Error("Validation error: durationNightsMin cannot be greater than durationNightsMax");
    }

    // Attach participant if there's a matching unclaimed invitation
    try {
      await attachParticipantToTrip(supabase, data.tripId, userId, emailRaw ?? "");
    } catch (e) {
      // attachParticipantToTrip throws if no pending invite exists; this is acceptable in some flows
      // We swallow the error here to allow users that are already attached (or owner) to continue.
      // If you prefer strict behavior, rethrow the error.
    }

    // Check if a preference row already exists to set submitted_at vs updated_at
    const existingPref = await supabase
      .from("trip_participant_preferences")
      .select("submitted_at, updated_at")
      .eq("trip_id", data.tripId)
      .eq("user_id", userId)
      .maybeSingle();
    if (existingPref.error) throw existingPref.error;
    assertQuestionnaireCanBeSubmitted(existingPref.data);

    const now = new Date().toISOString();

    const payload: any = {
      trip_id: data.tripId,
      user_id: userId,
      ambiances: (data as any).ambiances,
      activity_categories: (data as any).activityCategories,
      budget_max: (data as any).budgetMax ?? null,
      duration_nights_min: (data as any).durationNightsMin ?? null,
      duration_nights_max: (data as any).durationNightsMax ?? null,
      desired_destination: (data as any).desiredDestination ?? null,
      excluded_destinations: (data as any).excludedDestinations,
      dietary_constraints: (data as any).dietaryConstraints,
      mobility_notes: (data as any).mobilityNotes ?? null,
      free_text: (data as any).freeText ?? null,

      // map new fields to snake_case columns
      departure_city: (data as any).departureCity ?? null,
      departure_flex_km: (data as any).departureFlexKm ?? null,
      date_flex_days: (data as any).dateFlexDays ?? null,
      accepts_shared_room: (data as any).acceptsSharedRoom ?? false,
      room_type_preference: (data as any).roomTypePreference ?? null,
      required_amenities: (data as any).requiredAmenities ?? [],
      min_accommodation_rating: (data as any).minAccommodationRating ?? null,
      travel_pace: (data as any).travelPace ?? null,
      deal_breaker_ambiances: (data as any).dealBreakerAmbiances ?? [],
      departure_airport_or_station: (data as any).departureAirportOrStation ?? null,
      transport_mode_accepted: (data as any).transportModeAccepted ?? ["peu importe"],
      max_travel_duration_hours: (data as any).maxTravelDurationHours ?? null,
      accessibility_needs: (data as any).accessibilityNeeds ?? false,
      blackout_dates: (data as any).blackoutDates ?? [],
      budget_priority: (data as any).budgetPriority ?? "nice_to_have",
      preferred_time_slots: (data as any).preferredTimeSlots ?? [],
      group_age_range: (data as any).groupAgeRange ?? null,
      wanted_env_type: (data as any).wantedEnvType ?? null,
      weather_preference: (data as any).weatherPreference ?? 1,
      local_mobility: data.localMobility ?? null,
      accommodation_role: data.accommodationRole ?? null,
    };

    payload.submitted_at = now;
    payload.updated_at = null;

    // Sécurité : la ligne est toujours celle de l'utilisateur authentifié (jamais un autre user_id)
    payload.user_id = userId;
    payload.trip_id = data.tripId;

    const isUpdate = Boolean(existingPref.data);
    // Upsert résilient : si colonnes API manquantes en DB, retente avec le socle minimal
    let { error } = await supabase
      .from("trip_participant_preferences")
      .upsert(payload, { onConflict: "trip_id,user_id" });

    if (error) {
      const msg = String(error.message || error);
      const schemaIssue =
        msg.includes("schema cache") ||
        msg.includes("column") ||
        msg.includes("Could not find");

      if (schemaIssue) {
        const corePayload = {
          trip_id: data.tripId,
          user_id: userId,
          ambiances: (data as any).ambiances ?? [],
          activity_categories: (data as any).activityCategories ?? [],
          budget_max: (data as any).budgetMax ?? null,
          budget_priority: (data as any).budgetPriority ?? "nice_to_have",
          duration_nights_min: (data as any).durationNightsMin ?? null,
          duration_nights_max: (data as any).durationNightsMax ?? null,
          desired_destination: (data as any).desiredDestination ?? null,
          excluded_destinations: (data as any).excludedDestinations ?? [],
          dietary_constraints: (data as any).dietaryConstraints ?? [],
          mobility_notes: (data as any).mobilityNotes ?? null,
          free_text: (data as any).freeText ?? null,
          submitted_at: payload.submitted_at ?? now,
          updated_at: now,
          weather_preference: (data as any).weatherPreference ?? 1,
        };
        const retry = await supabase
          .from("trip_participant_preferences")
          .upsert(corePayload, { onConflict: "trip_id,user_id" });
        if (retry.error) {
          throw new Error(
            `Enregistrement préférences impossible: ${retry.error.message}. ` +
              "Exécute le SQL trip_participant_preferences dans Supabase.",
          );
        }
        error = null;
      } else {
        throw new Error(`Enregistrement préférences impossible: ${msg}`);
      }
    }

    const [participants, preferences] = await Promise.all([
      supabase.from("trip_participants").select("id").eq("trip_id", data.tripId),
      supabase.from("trip_participant_preferences").select("user_id").eq("trip_id", data.tripId),
    ]);
    if (participants.error) throw participants.error;
    if (preferences.error) throw preferences.error;

    const total = participants.data?.length ?? 0;
    const answered = new Set((preferences.data ?? []).map((preference: { user_id: string | null }) => preference.user_id).filter(Boolean)).size;
    // Questionnaire completion unlocks the profile step. Destination discovery
    // only starts after explicit organizer profile validation.
    return questionnaireCompletionResult({ isUpdate, answered, total });
  });

export async function getParticipantsProgressHelper(supabase: any, tripId: string) {
  const [tripRes, participants, preferences, availabilities, starPrefs] = await Promise.all([
    supabase.from("trips").select("participants_count, celebrated_person, has_star, star_user_id, owner_id, co_organizer_id").eq("id", tripId).maybeSingle(),
    supabase
      .from("trip_participants")
      .select("id, user_id, email, display_name, status")
      .eq("trip_id", tripId),
    supabase
      .from("trip_participant_preferences")
      .select("user_id, submitted_at, updated_at")
      .eq("trip_id", tripId),
    supabase
      .from("trip_availability")
      .select("user_id")
      .eq("trip_id", tripId),
    supabase
      .from("trip_star_preferences")
      .select("*")
      .eq("trip_id", tripId)
      .maybeSingle(),
  ]);
  if (tripRes.error) throw tripRes.error;
  if (participants.error) throw participants.error;

  const prefRows = preferences.error ? [] : (preferences.data ?? []);
  const prefMap = new Map<string, any>();
  for (const p of prefRows as any[]) {
    if (p.user_id) prefMap.set(p.user_id, p);
  }

  const availRows = availabilities.error ? [] : (availabilities.data ?? []);
  const availSet = new Set(availRows.map((r: any) => r.user_id).filter(Boolean));

  const celebratedPerson = tripRes.data?.celebrated_person;
  const hasStar = Boolean(tripRes.data?.has_star || celebratedPerson);

  const rawParticipants = participants.data ?? [];
  // Filter out absent participants
  const activeParticipants = rawParticipants.filter((p: any) => p.status !== "absent");

  // Find the star in the participants list strictly via star_user_id
  const starUserId = tripRes.data?.star_user_id || null;
  const starParticipant = starUserId
    ? activeParticipants.find((p: any) => p.user_id === starUserId) || null
    : null;

  // Resolve starUid safely (never use the form-filler's user ID, e.g. organizer, unless it's the actual star)
  const starUid = starParticipant?.user_id || starUserId || "star-virtual-uid";

  const starHasPrefs = starPrefs.data && (
    (starPrefs.data.wanted_activities && starPrefs.data.wanted_activities.length > 0) ||
    (starPrefs.data.ambiances && starPrefs.data.ambiances.length > 0) ||
    starPrefs.data.wanted_env_type ||
    starPrefs.data.desired_destination ||
    starPrefs.data.submitted_at
  );
  const starHasAvail = starPrefs.data && (
    (starPrefs.data.available_dates && starPrefs.data.available_dates.length > 0) ||
    (starPrefs.data.blocked_dates && starPrefs.data.blocked_dates.length > 0)
  );

  const partsList: any[] = [];
  const processedUserIds = new Set();

  // 1. Add active participants from DB
  for (const p of activeParticipants) {
    const isStar = p === starParticipant;
    let hasAnswered = p.user_id ? prefMap.has(p.user_id) : false;
    let hasAnsweredAvailability = p.user_id ? availSet.has(p.user_id) : false;

    if (isStar) {
      if (starHasPrefs) hasAnswered = true;
      if (starHasAvail) hasAnsweredAvailability = true;
    }

    partsList.push({
      ...p,
      display_name: isStar && celebratedPerson ? celebratedPerson : (p.display_name ?? p.email?.split("@")[0] ?? "Participant"),
      isStar,
      hasAnswered,
      hasAnsweredAvailability,
      answeredAt: isStar && starHasPrefs
        ? (starPrefs.data.updated_at || starPrefs.data.submitted_at)
        : (p.user_id && prefMap.has(p.user_id) ? (prefMap.get(p.user_id).updated_at || prefMap.get(p.user_id).submitted_at) : null),
    });

    if (p.user_id) processedUserIds.add(p.user_id);
  }

  // 2. Add virtual star if star is not in list but we have star details
  const starInList = partsList.some((p) => p.isStar);
  if (hasStar && !starInList) {
    partsList.push({
      id: "star-virtual-id",
      user_id: starUid,
      email: null,
      display_name: celebratedPerson || "La Star",
      status: "accepte",
      isStar: true,
      hasAnswered: !!starHasPrefs,
      hasAnsweredAvailability: !!starHasAvail,
      answeredAt: starHasPrefs ? (starPrefs.data.updated_at || starPrefs.data.submitted_at) : null,
    });
  }

  const baseExpected = Math.max(Number(tripRes.data?.participants_count) || 0, partsList.length, 1);
  const expected = baseExpected; // No extra counting for star!

  // 3. Fill the list with generic participants up to expected
  const currentLen = partsList.length;
  if (currentLen < expected) {
    for (let i = currentLen + 1; i <= expected; i++) {
      partsList.push({
        id: `generic-virtual-${i}`,
        user_id: null,
        email: null,
        display_name: `Participant ${i}`,
        status: "invite",
        isStar: false,
        hasAnswered: false,
        hasAnsweredAvailability: false,
        answeredAt: null,
      });
    }
  }

  const joined = activeParticipants.length;
  const answered = partsList.filter((p) => p.hasAnswered).length;
  const availabilityAnswered = partsList.filter((p) => p.hasAnsweredAvailability).length;

  return {
    joined,
    expected,
    total: expected,
    answered,
    availabilityAnswered,
    pendingPrefs: Math.max(expected - answered, 0),
    pendingJoin: Math.max(expected - joined, 0),
    participants: partsList,
  };
}

export const getParticipantsProgress = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { tripId: string }) => z.object({ tripId: z.string().uuid() }).parse(data))
  .handler(async ({ data, context }) => {
    const { supabase } = context;
    return getParticipantsProgressHelper(supabase, data.tripId);
  });
