// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - TanStack devtools (dev-only, first), tanstackStart, viteReact, tailwindcss, tsConfigPaths,
//     nitro (build-only using cloudflare as a default target), VITE_* env injection, @ path alias,
//     React/TanStack dedupe, error logger plugins, and sandbox detection (port/host/strictPort).
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { mcpPlugin } from "@lovable.dev/mcp-js/stacks/tanstack/vite";

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
  vite: {
    plugins: [mcpPlugin()],
    // Expose only the safe, client-side Supabase values generated by the Vercel integration.
    define: {
      "import.meta.env.NEXT_PUBLIC_krewproject_SUPABASE_URL": JSON.stringify(process.env.NEXT_PUBLIC_krewproject_SUPABASE_URL ?? ""),
      "import.meta.env.NEXT_PUBLIC_krewproject_SUPABASE_PUBLISHABLE_KEY": JSON.stringify(process.env.NEXT_PUBLIC_krewproject_SUPABASE_PUBLISHABLE_KEY ?? ""),
    },
  },
});
