/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiRecalibrateRouteImport } from './routes/api.recalibrate'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as JoinTripIdRouteImport } from './routes/join.$tripId'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated/trips.new'
import { Route as AuthenticatedTripsTripIdIndexRouteImport } from './routes/_authenticated/trips.$tripId.index'
import { Route as AuthenticatedTripsTripIdAvailabilityRouteImport } from './routes/_authenticated/trips.$tripId.availability'
import { Route as AuthenticatedTripsTripIdInviteRouteImport } from './routes/_authenticated/trips.$tripId.invite'
import { Route as AuthenticatedTripsTripIdMemoriesRouteImport } from './routes/_authenticated/trips.$tripId.memories'
import { Route as AuthenticatedTripsTripIdQuestionnaireRouteImport } from './routes/_authenticated/trips.$tripId.questionnaire'
import { Route as AuthenticatedTripsTripIdRecapRouteImport } from './routes/_authenticated/trips.$tripId.recap'
import { Route as AuthenticatedTripsTripIdStarRouteImport } from './routes/_authenticated/trips.$tripId.star'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRecalibrateRoute = ApiRecalibrateRouteImport.update({
  id: '/api/recalibrate',
  path: '/api/recalibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTripIdRoute = JoinTripIdRouteImport.update({
  id: '/join/$tripId',
  path: '/join/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsTripIdIndexRoute =
  AuthenticatedTripsTripIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdAvailabilityRoute =
  AuthenticatedTripsTripIdAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdInviteRoute =
  AuthenticatedTripsTripIdInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdMemoriesRoute =
  AuthenticatedTripsTripIdMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdQuestionnaireRoute =
  AuthenticatedTripsTripIdQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdRecapRoute =
  AuthenticatedTripsTripIdRecapRouteImport.update({
    id: '/recap',
    path: '/recap',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)
const AuthenticatedTripsTripIdStarRoute =
  AuthenticatedTripsTripIdStarRouteImport.update({
    id: '/star',
    path: '/star',
    getParentRoute: () => AuthenticatedTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/recalibrate': typeof ApiRecalibrateRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/join/$tripId': typeof JoinTripIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/trips/$tripId/availability': typeof AuthenticatedTripsTripIdAvailabilityRoute
  '/trips/$tripId/invite': typeof AuthenticatedTripsTripIdInviteRoute
  '/trips/$tripId/memories': typeof AuthenticatedTripsTripIdMemoriesRoute
  '/trips/$tripId/questionnaire': typeof AuthenticatedTripsTripIdQuestionnaireRoute
  '/trips/$tripId/recap': typeof AuthenticatedTripsTripIdRecapRoute
  '/trips/$tripId/star': typeof AuthenticatedTripsTripIdStarRoute
  '/trips/$tripId/': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/recalibrate': typeof ApiRecalibrateRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/join/$tripId': typeof JoinTripIdRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/trips/$tripId/availability': typeof AuthenticatedTripsTripIdAvailabilityRoute
  '/trips/$tripId/invite': typeof AuthenticatedTripsTripIdInviteRoute
  '/trips/$tripId/memories': typeof AuthenticatedTripsTripIdMemoriesRoute
  '/trips/$tripId/questionnaire': typeof AuthenticatedTripsTripIdQuestionnaireRoute
  '/trips/$tripId/recap': typeof AuthenticatedTripsTripIdRecapRoute
  '/trips/$tripId/star': typeof AuthenticatedTripsTripIdStarRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/recalibrate': typeof ApiRecalibrateRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/join/$tripId': typeof JoinTripIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRouteWithChildren
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/_authenticated/trips/$tripId/availability': typeof AuthenticatedTripsTripIdAvailabilityRoute
  '/_authenticated/trips/$tripId/invite': typeof AuthenticatedTripsTripIdInviteRoute
  '/_authenticated/trips/$tripId/memories': typeof AuthenticatedTripsTripIdMemoriesRoute
  '/_authenticated/trips/$tripId/questionnaire': typeof AuthenticatedTripsTripIdQuestionnaireRoute
  '/_authenticated/trips/$tripId/recap': typeof AuthenticatedTripsTripIdRecapRoute
  '/_authenticated/trips/$tripId/star': typeof AuthenticatedTripsTripIdStarRoute
  '/_authenticated/trips/$tripId/': typeof AuthenticatedTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs'
    | '/dashboard'
    | '/api/recalibrate'
    | '/api/stripe-webhook'
    | '/join/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/availability'
    | '/trips/$tripId/invite'
    | '/trips/$tripId/memories'
    | '/trips/$tripId/questionnaire'
    | '/trips/$tripId/recap'
    | '/trips/$tripId/star'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs'
    | '/dashboard'
    | '/api/recalibrate'
    | '/api/stripe-webhook'
    | '/join/$tripId'
    | '/trips/new'
    | '/trips/$tripId/availability'
    | '/trips/$tripId/invite'
    | '/trips/$tripId/memories'
    | '/trips/$tripId/questionnaire'
    | '/trips/$tripId/recap'
    | '/trips/$tripId/star'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs'
    | '/_authenticated/dashboard'
    | '/api/recalibrate'
    | '/api/stripe-webhook'
    | '/join/$tripId'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/new'
    | '/_authenticated/trips/$tripId/availability'
    | '/_authenticated/trips/$tripId/invite'
    | '/_authenticated/trips/$tripId/memories'
    | '/_authenticated/trips/$tripId/questionnaire'
    | '/_authenticated/trips/$tripId/recap'
    | '/_authenticated/trips/$tripId/star'
    | '/_authenticated/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  TarifsRoute: typeof TarifsRoute
  ApiRecalibrateRoute: typeof ApiRecalibrateRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  JoinTripIdRoute: typeof JoinTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/recalibrate': {
      id: '/api/recalibrate'
      path: '/api/recalibrate'
      fullPath: '/api/recalibrate'
      preLoaderRoute: typeof ApiRecalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$tripId': {
      id: '/join/$tripId'
      path: '/join/$tripId'
      fullPath: '/join/$tripId'
      preLoaderRoute: typeof JoinTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/$tripId/': {
      id: '/_authenticated/trips/$tripId/'
      path: '/'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof AuthenticatedTripsTripIdIndexRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/availability': {
      id: '/_authenticated/trips/$tripId/availability'
      path: '/availability'
      fullPath: '/trips/$tripId/availability'
      preLoaderRoute: typeof AuthenticatedTripsTripIdAvailabilityRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/invite': {
      id: '/_authenticated/trips/$tripId/invite'
      path: '/invite'
      fullPath: '/trips/$tripId/invite'
      preLoaderRoute: typeof AuthenticatedTripsTripIdInviteRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/memories': {
      id: '/_authenticated/trips/$tripId/memories'
      path: '/memories'
      fullPath: '/trips/$tripId/memories'
      preLoaderRoute: typeof AuthenticatedTripsTripIdMemoriesRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/questionnaire': {
      id: '/_authenticated/trips/$tripId/questionnaire'
      path: '/questionnaire'
      fullPath: '/trips/$tripId/questionnaire'
      preLoaderRoute: typeof AuthenticatedTripsTripIdQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/recap': {
      id: '/_authenticated/trips/$tripId/recap'
      path: '/recap'
      fullPath: '/trips/$tripId/recap'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRecapRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
    '/_authenticated/trips/$tripId/star': {
      id: '/_authenticated/trips/$tripId/star'
      path: '/star'
      fullPath: '/trips/$tripId/star'
      preLoaderRoute: typeof AuthenticatedTripsTripIdStarRouteImport
      parentRoute: typeof AuthenticatedTripsTripIdRoute
    }
  }
}

interface AuthenticatedTripsTripIdRouteChildren {
  AuthenticatedTripsTripIdAvailabilityRoute: typeof AuthenticatedTripsTripIdAvailabilityRoute
  AuthenticatedTripsTripIdInviteRoute: typeof AuthenticatedTripsTripIdInviteRoute
  AuthenticatedTripsTripIdMemoriesRoute: typeof AuthenticatedTripsTripIdMemoriesRoute
  AuthenticatedTripsTripIdQuestionnaireRoute: typeof AuthenticatedTripsTripIdQuestionnaireRoute
  AuthenticatedTripsTripIdRecapRoute: typeof AuthenticatedTripsTripIdRecapRoute
  AuthenticatedTripsTripIdStarRoute: typeof AuthenticatedTripsTripIdStarRoute
  AuthenticatedTripsTripIdIndexRoute: typeof AuthenticatedTripsTripIdIndexRoute
}

const AuthenticatedTripsTripIdRouteChildren: AuthenticatedTripsTripIdRouteChildren =
  {
    AuthenticatedTripsTripIdAvailabilityRoute:
      AuthenticatedTripsTripIdAvailabilityRoute,
    AuthenticatedTripsTripIdInviteRoute: AuthenticatedTripsTripIdInviteRoute,
    AuthenticatedTripsTripIdMemoriesRoute:
      AuthenticatedTripsTripIdMemoriesRoute,
    AuthenticatedTripsTripIdQuestionnaireRoute:
      AuthenticatedTripsTripIdQuestionnaireRoute,
    AuthenticatedTripsTripIdRecapRoute: AuthenticatedTripsTripIdRecapRoute,
    AuthenticatedTripsTripIdStarRoute: AuthenticatedTripsTripIdStarRoute,
    AuthenticatedTripsTripIdIndexRoute: AuthenticatedTripsTripIdIndexRoute,
  }

const AuthenticatedTripsTripIdRouteWithChildren =
  AuthenticatedTripsTripIdRoute._addFileChildren(
    AuthenticatedTripsTripIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRouteWithChildren
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRouteWithChildren,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  TarifsRoute: TarifsRoute,
  ApiRecalibrateRoute: ApiRecalibrateRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  JoinTripIdRoute: JoinTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
