// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session

    // Only refresh when the current access token is actually close to expiry.
    // Do not refresh on every server-function call: that can race with other
    // Supabase auth requests and cause the server function to receive a stale
    // JWT while the client has already rotated its session.
    if (session?.expires_at) {
      const expiresIn = session.expires_at * 1000 - Date.now()
      if (expiresIn > 0 && expiresIn < 60_000) {
        const refreshed = await supabase.auth.refreshSession()
        session = refreshed.data.session ?? session
      }
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
