// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) headers.delete('Authorization');
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(async ({ next }) => {
  // Prefer the exact same public project URL/key pair used by the browser.
  // This prevents the server from authenticating against a different/stale
  // Supabase API key when the Vercel/Supabase integration exposes multiple names.
  const SUPABASE_URL =
    process.env['NEXT_PUBLIC_krewproject_SUPABASE_URL'] ||
    process.env['krewproject_SUPABASE_URL'] ||
    process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY =
    process.env['NEXT_PUBLIC_krewproject_SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['krewproject_SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['krewproject_SUPABASE_ANON_KEY'] ||
    process.env['SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['SUPABASE_ANON_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Missing Supabase environment variables from the Vercel/Supabase integration.');
  }

  const request = getRequest();
  if (!request?.headers) throw new Error('Unauthorized: No request headers available');
  const authHeader = request.headers.get('authorization');
  if (!authHeader?.startsWith('Bearer ')) throw new Error('Unauthorized: Bearer token required');

  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token || token.split('.').length !== 3) throw new Error('Unauthorized: Invalid token');

  const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY), headers: { Authorization: `Bearer ${token}` } },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data?.user) {
    console.error('[Supabase Auth Middleware Error] failed to getUser from token:', error);
    throw new Error('Unauthorized: Invalid token');
  }

  return next({
    context: {
      supabase,
      userId: data.user.id,
      claims: { sub: data.user.id, email: data.user.email, role: data.user.role, user_metadata: data.user.user_metadata, ...data.user },
    },
  });
});
