import { describe, expect, it, vi } from "vitest";
import { questionnaireCompletionResult } from "../participant-preferences.functions";
import { materializeFinalDestinations, replaceRecommendationsSafely, requiresLegacyProfileValidation, selectTopDestinationProposals, serializeProposal } from "../krew/trip-service";
import { selectDiverseTop, type Proposal } from "../krew/engine";

const proposal = (name: string, score: number, country = "France") => ({
  destination: { id: name, name, country }, score,
  budget: { totalPerPerson: 500 },
}) as unknown as Proposal;

describe("pipeline finalization", () => {
  const uuid = "123e4567-e89b-42d3-a456-426614174000";
  it("does not auto-generate destinations after questionnaire completion", () => {
    expect(questionnaireCompletionResult({ isUpdate: false, answered: 2, total: 4 })).toMatchObject({
      autoGenerated: false,
      nextStep: "profile",
    });
  });

  it("requires profile validation before regenerating a legacy trip without concepts", () => {
    expect(requiresLegacyProfileValidation({ questionnairesReady: true, validated: true, legacyBypass: true, calculatedConcepts: [], selectedConcepts: [] })).toBe(true);
    expect(requiresLegacyProfileValidation({ questionnairesReady: true, validated: true, legacyBypass: false, calculatedConcepts: [], selectedConcepts: [{ id: "city" }] })).toBe(false);
  });

  it("keeps old recommendations when inserting replacements fails", async () => {
    const deleteSpy = vi.fn();
    const supabase = {
      from: () => ({
        select: () => ({ eq: async () => ({ data: [{ id: "old" }], error: null }) }),
        insert: () => ({ select: async () => ({ data: null, error: new Error("insert failed") }) }),
        delete: deleteSpy,
      }),
    };
    await expect(replaceRecommendationsSafely(supabase as any, "trip", [{ destination_id: uuid } as any])).rejects.toThrow("insert failed");
    expect(deleteSpy).not.toHaveBeenCalled();
  });

  it("inserts valid replacements before deleting old recommendations", async () => {
    const events: string[] = [];
    const supabase = {
      from: () => ({
        select: () => ({ eq: async () => ({ data: [{ id: "old" }], error: null }) }),
        insert: () => ({ select: async () => { events.push("insert"); return { data: [{ id: "new" }], error: null }; } }),
        delete: () => ({ in: async () => { events.push("delete"); return { error: null }; } }),
      }),
    };
    await replaceRecommendationsSafely(supabase as any, "trip", [{ destination_id: uuid } as any]);
    expect(events).toEqual(["insert", "delete"]);
  });

  it("never replaces a much better candidate for artificial diversity", () => {
    const ranked = selectDiverseTop([
      proposal("Best", 93, "France"), proposal("Second", 91, "France"), proposal("Diverse weak", 78, "Italie"),
    ], 2);
    expect(ranked.map((item) => item.score)).toEqual([93, 91]);
  });

  it("keeps deterministic score order for near ties", () => {
    const ranked = selectDiverseTop([proposal("A", 93), proposal("B", 92), proposal("C", 91)], 3);
    expect(ranked.map((item) => item.score)).toEqual([93, 92, 91]);
  });

  it("retains the established four-destination output limit", () => {
    const ranked = selectTopDestinationProposals([95, 94, 93, 92, 91].map((score) => proposal(String(score), score)), 4);
    expect(ranked).toHaveLength(4);
  });

  it("keeps only the best configuration for each final destination", () => {
    const ranked = selectTopDestinationProposals([
      proposal("Paris", 95), proposal("Paris", 93), proposal("Lyon", 92),
    ], 4);
    expect(ranked.map((item) => item.destination.id)).toEqual(["Paris", "Lyon"]);
  });

  it("does not query Supabase for an already persisted destination UUID", async () => {
    const from = vi.fn();
    const result = await materializeFinalDestinations({ from } as any, [proposal(uuid, 90)]);
    expect(result[0]?.destination.id).toBe(uuid);
    expect(from).not.toHaveBeenCalled();
  });

  it("upserts a missing discovery finalist and replaces its temporary ID", async () => {
    const upsert = vi.fn((_payload: unknown, _options: unknown) => ({ select: () => ({ single: async () => ({ data: { id: uuid }, error: null }) }) }));
    const builder = { select: () => builder, eq: () => builder, ilike: () => builder, maybeSingle: async () => ({ data: null, error: null }), upsert };
    const input = proposal("discovery:test-destination", 90);
    input.destination.slug = "test-destination";
    input.destination.source = "krew_discovery";
    const result = await materializeFinalDestinations({ from: () => builder } as any, [input]);
    expect(upsert).toHaveBeenCalledTimes(1);
    expect(upsert.mock.calls[0]?.[1]).toEqual({ onConflict: "slug" });
    expect(result[0]?.destination.id).toBe(uuid);
  });

  it("reuses a destination found by source and external_id", async () => {
    const upsert = vi.fn();
    const builder = { select: () => builder, eq: () => builder, ilike: () => builder, maybeSingle: async () => ({ data: { id: uuid }, error: null }), upsert };
    const input = proposal("discovery:test-source", 90);
    input.destination.slug = "test-source";
    input.destination.source = "ai_estimate";
    (input.destination as any).external_id = "ai:test-source";
    const result = await materializeFinalDestinations({ from: () => builder } as any, [input]);
    expect(result[0]?.destination.id).toBe(uuid);
    expect(upsert).not.toHaveBeenCalled();
  });

  it("reuses an already materialized discovery destination without duplication", async () => {
    const upsert = vi.fn();
    const builder = { select: () => builder, eq: () => builder, ilike: () => builder, maybeSingle: async () => ({ data: { id: uuid }, error: null }), upsert };
    const input = proposal("discovery:test-destination", 90);
    input.destination.slug = "test-destination";
    const result = await materializeFinalDestinations({ from: () => builder } as any, [input]);
    expect(result[0]?.destination.id).toBe(uuid);
    expect(upsert).not.toHaveBeenCalled();
  });

  it("blocks temporary IDs and serializes only materialized UUIDs", () => {
    expect(() => serializeProposal("trip", proposal("discovery:test", 90))).toThrow("final_destination_not_persisted");
    const complete = { ...proposal(uuid, 90), accommodation: null, activities: [], rationale: "compatible", matchReasons: [], itinerary: [], budget: {}, subScores: {}, consensusScore: 0.8, minSatisfaction: 0.7, satisfiedCount: 4, participantsEvaluated: 4 } as unknown as Proposal;
    expect(serializeProposal("trip", complete).destination_id).toBe(uuid);
  });

});
