import { describe, expect, it, vi } from "vitest";
import { questionnaireCompletionResult } from "../participant-preferences.functions";
import { replaceRecommendationsSafely, requiresLegacyProfileValidation, selectTopDestinationProposals } from "../krew/trip-service";
import { selectDiverseTop, type Proposal } from "../krew/engine";

const proposal = (name: string, score: number, country = "France") => ({
  destination: { id: name, name, country }, score,
  budget: { totalPerPerson: 500 },
}) as unknown as Proposal;

describe("pipeline finalization", () => {
  it("does not auto-generate destinations after questionnaire completion", () => {
    expect(questionnaireCompletionResult({ isUpdate: false, answered: 2, total: 4 })).toMatchObject({
      autoGenerated: false,
      nextStep: "profile",
    });
  });

  it("requires profile validation before regenerating a legacy trip without concepts", () => {
    expect(requiresLegacyProfileValidation({ questionnairesReady: true, validated: true, legacyBypass: true, calculatedConcepts: [], selectedConcepts: [] })).toBe(true);
    expect(requiresLegacyProfileValidation({ questionnairesReady: true, validated: true, legacyBypass: false, calculatedConcepts: [], selectedConcepts: [{ id: "city" }] })).toBe(false);
  });

  it("keeps old recommendations when inserting replacements fails", async () => {
    const deleteSpy = vi.fn();
    const supabase = {
      from: () => ({
        select: () => ({ eq: async () => ({ data: [{ id: "old" }], error: null }) }),
        insert: () => ({ select: async () => ({ data: null, error: new Error("insert failed") }) }),
        delete: deleteSpy,
      }),
    };
    await expect(replaceRecommendationsSafely(supabase as any, "trip", [{} as any])).rejects.toThrow("insert failed");
    expect(deleteSpy).not.toHaveBeenCalled();
  });

  it("inserts valid replacements before deleting old recommendations", async () => {
    const events: string[] = [];
    const supabase = {
      from: () => ({
        select: () => ({ eq: async () => ({ data: [{ id: "old" }], error: null }) }),
        insert: () => ({ select: async () => { events.push("insert"); return { data: [{ id: "new" }], error: null }; } }),
        delete: () => ({ in: async () => { events.push("delete"); return { error: null }; } }),
      }),
    };
    await replaceRecommendationsSafely(supabase as any, "trip", [{} as any]);
    expect(events).toEqual(["insert", "delete"]);
  });

  it("never replaces a much better candidate for artificial diversity", () => {
    const ranked = selectDiverseTop([
      proposal("Best", 93, "France"), proposal("Second", 91, "France"), proposal("Diverse weak", 78, "Italie"),
    ], 2);
    expect(ranked.map((item) => item.score)).toEqual([93, 91]);
  });

  it("keeps deterministic score order for near ties", () => {
    const ranked = selectDiverseTop([proposal("A", 93), proposal("B", 92), proposal("C", 91)], 3);
    expect(ranked.map((item) => item.score)).toEqual([93, 92, 91]);
  });

  it("retains the established four-destination output limit", () => {
    const ranked = selectTopDestinationProposals([95, 94, 93, 92, 91].map((score) => proposal(String(score), score)), 4);
    expect(ranked).toHaveLength(4);
  });

  it("keeps only the best configuration for each final destination", () => {
    const ranked = selectTopDestinationProposals([
      proposal("Paris", 95), proposal("Paris", 93), proposal("Lyon", 92),
    ], 4);
    expect(ranked.map((item) => item.destination.id)).toEqual(["Paris", "Lyon"]);
  });
});
